// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/zakiyalmaya/cryptocurrencies-price-tracker/model"
)

// MockCoinCapService is a mock of CoinCapService interface.
type MockCoinCapService struct {
	ctrl     *gomock.Controller
	recorder *MockCoinCapServiceMockRecorder
}

// MockCoinCapServiceMockRecorder is the mock recorder for MockCoinCapService.
type MockCoinCapServiceMockRecorder struct {
	mock *MockCoinCapService
}

// NewMockCoinCapService creates a new mock instance.
func NewMockCoinCapService(ctrl *gomock.Controller) *MockCoinCapService {
	mock := &MockCoinCapService{ctrl: ctrl}
	mock.recorder = &MockCoinCapServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinCapService) EXPECT() *MockCoinCapServiceMockRecorder {
	return m.recorder
}

// GetAsset mocks base method.
func (m *MockCoinCapService) GetAsset(coinID string) (*model.AssetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", coinID)
	ret0, _ := ret[0].(*model.AssetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockCoinCapServiceMockRecorder) GetAsset(coinID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockCoinCapService)(nil).GetAsset), coinID)
}

// GetAssets mocks base method.
func (m *MockCoinCapService) GetAssets(req *model.AssetRequest) (*model.AssetsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssets", req)
	ret0, _ := ret[0].(*model.AssetsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssets indicates an expected call of GetAssets.
func (mr *MockCoinCapServiceMockRecorder) GetAssets(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssets", reflect.TypeOf((*MockCoinCapService)(nil).GetAssets), req)
}
